name: merdeka_quiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  appwrite: ^11.0.1
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bg/
    - assets/menu/
    - assets/bpupki/
    - assets/rengasdengklok/
    - assets/perumusan/
    - assets/yamato/
